### ISSUE TITLE
Error when complie

### ISSUE THREAD

**Issue by m2mlorawan** [pulsartronic/LoRaWANGatewaySC#5]
Found this error when complie.
C:\Users\sx\Documents\Arduino2\libraries\arduinoWebSockets-master\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::loop()':
C:\Users\sx\Documents\Arduino2\libraries\arduinoWebSockets-master\src\WebSocketsClient.cpp:172:30: error: 'class BearSSL::WiFiClientSecure' has no member named 'setCACert'
  172 |                 _client.ssl->setCACert((const uint8_t *)_CA_cert, strlen(_CA_cert) + 1);
      |                              ^~~~~~~~~
C:\Users\sx\Documents\Arduino2\libraries\arduinoWebSockets-master\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::connectedCb()':
C:\Users\sx\Documents\Arduino2\libraries\arduinoWebSockets-master\src\WebSocketsClient.cpp:759:26: error: 'class BearSSL::WiFiClientSecure' has no member named 'verify'
  759 |         if(!_client.ssl->verify(_fingerprint.c_str(), _host.c_str())) {

**Comment by pulsartronic** [comment]
Hello @m2mlorawan 
It is caused by the ESP8266 library version.
Oldest tested version is v2.6.3. Latest tested version is 2.7.1 ... you can find it under tools --> Board --> Board Manager
Search for that text here:
https://www.hackster.io/pulsartronic/lorawan-gateway-esp8266-rfm95-arduino-4914a8

Another work around is to update this library:
https://github.com/Links2004/arduinoWebSockets

**Comment by HemjalCF** [comment]
Please add that version info in your readme file. Your program doesn't compile on esp8266 v3.7.1
